# SPDX-FileCopyrightText: Copyright (c) 2024-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
    - 'vendor/**/**'
  DisplayCopNames: true
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  NewCops: enable
Style/OptionalBooleanParameter:
  Enabled: false
Lint/NestedMethodDefinition:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EndOfLine:
  EnforcedStyle: lf
require:
  - rubocop-rake
  - rubocop-minitest
